// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_emMpIzUBuw91p2GXNwP6-4QbxkXWt14',
    appId: '1:1048132034822:web:0501a5ee0e7f8845da3e87',
    messagingSenderId: '1048132034822',
    projectId: 'healthmonitoring-1fad4',
    authDomain: 'healthmonitoring-1fad4.firebaseapp.com',
    storageBucket: 'healthmonitoring-1fad4.firebasestorage.app',
    measurementId: 'G-88QML7EXXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiYgLAhvwyZpR6Dh-EvrcltpW2QWTbfU4',
    appId: '1:1048132034822:android:6e1e63e844bf55f9da3e87',
    messagingSenderId: '1048132034822',
    projectId: 'healthmonitoring-1fad4',
    storageBucket: 'healthmonitoring-1fad4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_emMpIzUBuw91p2GXNwP6-4QbxkXWt14',
    appId: '1:1048132034822:web:dab49bcadf76afcada3e87',
    messagingSenderId: '1048132034822',
    projectId: 'healthmonitoring-1fad4',
    authDomain: 'healthmonitoring-1fad4.firebaseapp.com',
    storageBucket: 'healthmonitoring-1fad4.firebasestorage.app',
    measurementId: 'G-KG3LDXK708',
  );
}
